# proto-file: experimental/users/chechenglin/tcpgpudmad/proto/gpu_rxq_configuration.proto
# proto-message: GpuRxqConfigurationList

gpu_rxq_configs {
  gpu_pci_addr: "0000:1d:00.0"
  nic_pci_addr: "0000:0a:00.0"
  ifname: "dcn1"
  rx_queue_ids: 0
  rx_queue_ids: 1
  rx_queue_ids: 2
  rx_queue_ids: 3
  rx_queue_ids: 4
  rx_queue_ids: 5
  rx_queue_ids: 6
  rx_queue_ids: 7
  rx_queue_ids: 8
  rx_queue_ids: 9
  rx_queue_ids: 10
  rx_queue_ids: 11
  rx_queue_ids: 12
  rx_queue_ids: 13
}
gpu_rxq_configs {
  gpu_pci_addr: "0000:51:00.0"
  nic_pci_addr: "0000:43:00.0"
  ifname: "dcn2"
  rx_queue_ids: 0
  rx_queue_ids: 1
  rx_queue_ids: 2
  rx_queue_ids: 3
  rx_queue_ids: 4
  rx_queue_ids: 5
  rx_queue_ids: 6
  rx_queue_ids: 7
  rx_queue_ids: 8
  rx_queue_ids: 9
  rx_queue_ids: 10
  rx_queue_ids: 11
  rx_queue_ids: 12
  rx_queue_ids: 13
}
gpu_rxq_configs {
  gpu_pci_addr: "0000:96:00.0"
  nic_pci_addr: "0000:88:00.0"
  ifname: "dcn3"
  rx_queue_ids: 0
  rx_queue_ids: 1
  rx_queue_ids: 2
  rx_queue_ids: 3
  rx_queue_ids: 4
  rx_queue_ids: 5
  rx_queue_ids: 6
  rx_queue_ids: 7
  rx_queue_ids: 8
  rx_queue_ids: 9
  rx_queue_ids: 10
  rx_queue_ids: 11
  rx_queue_ids: 12
  rx_queue_ids: 13
}
gpu_rxq_configs {
  gpu_pci_addr: "0000:c9:00.0"
  nic_pci_addr: "0000:bb:00.0"
  ifname: "dcn4"
  rx_queue_ids: 0
  rx_queue_ids: 1
  rx_queue_ids: 2
  rx_queue_ids: 3
  rx_queue_ids: 4
  rx_queue_ids: 5
  rx_queue_ids: 6
  rx_queue_ids: 7
  rx_queue_ids: 8
  rx_queue_ids: 9
  rx_queue_ids: 10
  rx_queue_ids: 11
  rx_queue_ids: 12
  rx_queue_ids: 13
}
