#!/bin/sh

set -ex

alias gcloud_command='/google/data/ro/teams/cloud-sdk/gcloud alpha'

while true; do
  case "$1" in
    -s)
      alias gcloud_command='CLOUDSDK_API_CLIENT_OVERRIDES_COMPUTE=staging_v1 /google/data/ro/teams/cloud-sdk/gcloud'
      shift 1
      ;;
    *)
      break;
      ;;
  esac
done

pids=()
while true; do
  instance=$1
  if [ -z $instance ]; then
    break
  fi

  farray=$(ls ./scripts | grep -v copy-test-cos)

  for f in $farray; do
    gcloud_command compute scp \
      ./scripts/$f $instance:~/ &
    pids+=("$!")
  done

  gcloud_command compute ssh $instance -- \
    "sudo mount -o remount,exec /home/ && \
     cd ~/ && \
     sudo docker-credential-gcr configure-docker && \
     sudo iptables -I INPUT -p tcp -m tcp -j ACCEPT"

  shift || break
done

wait "${pids[@]}"
echo
echo
echo
echo
echo done copying...
