#!/bin/bash

function run_docker_connection_test() {
  docker run --pull=always -it --rm \
    -u 0 --network=host \
    --cap-add=IPC_LOCK \
    --volume /tmp:/tmp \
    --volume /var/lib/nvidia/lib64:/usr/local/nvidia/lib64 \
    --device /dev/nvidia0:/dev/nvidia0 \
    --device /dev/nvidia1:/dev/nvidia1 \
    --device /dev/nvidia2:/dev/nvidia2 \
    --device /dev/nvidia3:/dev/nvidia3 \
    --device /dev/nvidia4:/dev/nvidia4 \
    --device /dev/nvidia5:/dev/nvidia5 \
    --device /dev/nvidia6:/dev/nvidia6 \
    --device /dev/nvidia7:/dev/nvidia7 \
    --device /dev/nvidia-uvm:/dev/nvidia-uvm \
    --device /dev/nvidiactl:/dev/nvidiactl \
    --env LD_LIBRARY_PATH=/usr/local/nvidia/lib64 \
    --entrypoint /tcpgpudmarxd/build/machine_test/test/tcpx_single_connection_tests \
    gcr.io/a3-tcpd-staging-hostpool/$USER/machine_test "$@"
}

# Remount /var so we can actually load cuda libraries.
mount -o remount,exec /var && \

run_docker_connection_test "$@"
