#!/bin/sh

set -ex

MTU=$1

set_route_mtu() {
  echo setting route mtu to: $MTU
  src_ip=""
  dest_ip=""
  if [ -z $IS_SERVER ]; then
    echo Setting up routes for client...
    dest_ip=$CLIENT
    src_ip=$SERVER
  else
    echo Setting up routes for server...
    src_ip=$CLIENT
    dest_ip=$SERVER
  fi
  for i in 1 2 3 4; do
    interface=eth$i
    new_dest_ip=${dest_ip/.0./.$i.}

    ip route replace 192.168.$i.0/24 via 192.168.$i.1 dev $interface src \
      $new_dest_ip metric 1024 mtu lock $MTU pref medium

    # This is intentionally commented out as I'm not sure we need to set the
    # MTU to the gateway.
<<FUB
    ip route replace 192.168.$i.1 dev $interface proto dhcp scope link src \
      $new_dest_ip metric 1024 mtu lock $MTU pref medium
FUB
  done
}

set_link_mtu() {
  MTU=$1
  echo setting link mtu $MTU...
  for i in 0 1 2 3 4; do
    interface=eth$i
    new_dest_ip=${dest_ip/.0./.$i.}

    ip link set $interface mtu $MTU;
  done
}

set_route_mtu $MTU
set_link_mtu $MTU
