#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

set -ex

setup_nic_for_gpu () {
  local nic_ifname=$1;
  ethtool -G $nic_ifname rx 2048;
}

configure_big_tcp() {
  local size=$1
  echo Configuring big tcp to: $size
  for ifname in eth1 eth2 eth3 eth4
  do
    ip link set dev $ifname gro_max_size $size
    ip link set dev $ifname gso_max_size $size
  done
}

NUM_Q=16

# TODO gVNIC doesn't support `ethtool -G`.
# setup_nic_for_gpu eth1
# setup_nic_for_gpu eth2
# setup_nic_for_gpu eth3
# setup_nic_for_gpu eth4

# TODO COS doesn't yet support big TCP
# configure_big_tcp 181000

./tune_net_params_cos

echo 0 > /proc/sys/net/ipv4/tcp_mtu_probing

SERVER=$SERVER CLIENT=$CLIENT IS_SERVER=$IS_SERVER ./setmtu_cos $MTU
